[package]
name = "graphcal-eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
base64.workspace = true
graphcal-compiler = { workspace = true }
graphcal-io = { workspace = true }
graphcal-package = { workspace = true }
hifitime.workspace = true
indexmap.workspace = true
jiff.workspace = true
miette.workspace = true
num-rational = "0.4.2"
num-traits = "0.2.19"
petgraph = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
graphcal-compiler = { workspace = true, features = ["test-cancellation"] }
graphcal-test-support.workspace = true
insta.workspace = true
proptest.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
