//! Generic desugaring pipeline.
//!
//! Transforms `File<Raw>` (parser output, with all surface sugar) into
//! `File<Desugared>` (canonical form consumed by name resolution, IR lowering,
//! TIR, and evaluation).
//!
//! # Architecture
//!
//! The AST is rebuilt phase-by-phase through `From<T<Raw>> for
//! T<Desugared>` impls. Mechanical pass-throughs are generated by
//! `#[derive(PhaseLift)]` on the AST types; [`convert`] holds the
//! conversions with real logic, including the `Sugar(_)` lowerings, and
//! `multi` expands multi-declarations.
//!
//! ```text
//! File<Raw> ──┬─► convert ──┬─► File<Desugared>
//!             │             │
//!             ├─ MultiDecl ─┘ (one-to-many declarations, via `multi`)
//!             └─ TableLiteral ─► MapLiteral
//! ```
//!
//! The pass is the `From<File<Raw>> for File<Desugared>` impl:
//! `desugared_ast::File::from(raw_file)`.
//!
//! # Adding new sugar
//!
//! 1. Add a variant to [`crate::syntax::ast::RawDeclSugar`] or
//!    [`crate::syntax::ast::RawExprSugar`].
//! 2. Lower it in [`convert`]: declaration sugar in `convert_decl` (the
//!    `Err` arm of the derived `DeclKind` `TryFrom`),
//!    expression sugar in `From<RawExprSugar> for ExprKind<Desugared>`
//!    (the derived `ExprKind` conversion dispatches its `Sugar` variant
//!    there).
//!
//! No changes to downstream consumers are needed — they only see
//! `File<Desugared>` and never observe the sugar in the first place.
//!
//! # Span fidelity
//!
//! Desugaring preserves source spans: every synthesized node carries the
//! span of the surface construct it came from. Diagnostics emitted on
//! desugared AST still point at the original source.

pub mod convert;
pub mod desugared_ast;
mod multi;
