[package]
name = "graphcal-ratio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Reduced fixed-width rational numbers for Graphcal dimension exponents"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
proptest.workspace = true
