[graph]
all-features = true

[advisories]
ignore = []

[licenses]
include-dev = true
confidence-threshold = 0.8
unused-allowed-license = "allow"
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "NCSA",
  "Unicode-3.0",
  "Unlicense",
  "Zlib"
]
exceptions = [
  { allow = ["MPL-2.0"], crate = "hifitime@4" }
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "simplest-path"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
